#!/bin/bash
url=`cmus-remote -Q 2>/dev/null | grep 'file' | cut -d " " -f 2-`
content=$(cat ~/.conky/now-playing/npart2.txt)
if [ "$content" != "$url" ]; then
echo $url > ~/.conky/now-playing/npart2.txt
ffmpeg -y -i "$url" -an -vcodec copy ~/.conky/now-playing/npart2.jpg
fi